# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  scheme: 'TokenUI'

steps:
- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'build'
    scheme: 'TokenUIDemo'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath


- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
    destinationSimulators: 'iPhone XS'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'